INSERT INTO Regiones (PaisId, Nombre) VALUES
(3, N'Azerbaijan'),
(3, N'Nargorni Karabakh'),
(3, N'Nakhichevanskaya Region'),
(4, N'Anguilla'),
(7, N'Brestskaya obl.'),
(7, N'Vitebskaya obl.'),
(7, N'Gomelskaya obl.'),
(7, N'Grodnenskaya obl.'),
(7, N'Minskaya obl.'),
(7, N'Mogilevskaya obl.'),
(8, N'Belize'),
(10, N'Hamilton'),
(15, N'Dong Bang Song Cuu Long'),
(15, N'Dong Bang Song Hong'),
(15, N'Dong Nam Bo'),
(15, N'Duyen Hai Mien Trung'),
(15, N'Khu Bon Cu'),
(15, N'Mien Nui Va Trung Du'),
(15, N'Thai Nguyen'),
(16, N'Artibonite'),
(16, N'Grand&#039;Anse'),
(16, N'North West'),
(16, N'West'),
(16, N'South'),
(16, N'South East'),
(17, N'Grande-Terre'),
(17, N'Basse-Terre'),
(21, N'Abkhazia'),
(21, N'Ajaria'),
(21, N'Georgia'),
(21, N'South Ossetia'),
(23, N'El Cairo'),
(23, N'Aswan'),
(23, N'Asyut'),
(23, N'Beni Suef'),
(23, N'Gharbia'),
(23, N'Damietta'),
(24, N'Southern District'),
(24, N'Central District'),
(24, N'Northern District'),
(24, N'Haifa'),
(24, N'Tel Aviv'),
(24, N'Jerusalem'),
(25, N'Bangala'),
(25, N'Chhattisgarh'),
(25, N'Karnataka'),
(25, N'Uttaranchal'),
(25, N'Andhara Pradesh'),
(25, N'Assam'),
(25, N'Bihar'),
(25, N'Gujarat'),
(25, N'Jammu and Kashmir'),
(25, N'Kerala'),
(25, N'Madhya Pradesh'),
(25, N'Manipur'),
(25, N'Maharashtra'),
(25, N'Megahalaya'),
(25, N'Orissa'),
(25, N'Punjab'),
(25, N'Pondisheri'),
(25, N'Rajasthan'),
(25, N'Tamil Nadu'),
(25, N'Tripura'),
(25, N'Uttar Pradesh'),
(25, N'Haryana'),
(25, N'Chandigarh'),
(26, N'Azarbayjan-e Khavari'),
(26, N'Esfahan'),
(26, N'Hamadan'),
(26, N'Kordestan'),
(26, N'Markazi'),
(26, N'Sistan-e Baluches'),
(26, N'Yazd'),
(26, N'Kerman'),
(26, N'Kermanshakhan'),
(26, N'Mazenderan'),
(26, N'Tehran'),
(26, N'Fars'),
(26, N'Horasan'),
(26, N'Husistan'),
(30, N'Aktyubinskaya obl.'),
(30, N'Alma-Atinskaya obl.'),
(30, N'Vostochno-Kazahstanskaya obl.'),
(30, N'Gurevskaya obl.'),
(30, N'Zhambylskaya obl. (Dzhambulskaya obl.)'),
(30, N'Dzhezkazganskaya obl.'),
(30, N'Karagandinskaya obl.'),
(30, N'Kzyl-Ordinskaya obl.'),
(30, N'Kokchetavskaya obl.'),
(30, N'Kustanaiskaya obl.'),
(30, N'Mangystauskaya (Mangyshlakskaya obl.)'),
(30, N'Pavlodarskaya obl.'),
(30, N'Severo-Kazahstanskaya obl.'),
(30, N'Taldy-Kurganskaya obl.'),
(30, N'Turgaiskaya obl.'),
(30, N'Akmolinskaya obl. (Tselinogradskaya obl.)'),
(30, N'Chimkentskaya obl.'),
(31, N'Littoral'),
(31, N'Southwest Region'),
(31, N'North'),
(31, N'Central'),
(33, N'Government controlled area'),
(33, N'Turkish controlled area'),
(34, N'Issik Kulskaya Region'),
(34, N'Kyrgyzstan'),
(34, N'Narinskaya Region'),
(34, N'Oshskaya Region'),
(34, N'Tallaskaya Region'),
(37, N'al-Jahra'),
(37, N'al-Kuwait'),
(38, N'Latviya'),
(39, N'Tarabulus'),
(39, N'Bengasi'),
(40, N'Litva'),
(43, N'Moldova'),
(45, N'Auckland'),
(45, N'Bay of Plenty'),
(45, N'Canterbury'),
(45, N'Gisborne'),
(45, N'Hawke&#039;s Bay'),
(45, N'Manawatu-Wanganui'),
(45, N'Marlborough'),
(45, N'Nelson'),
(45, N'Northland'),
(45, N'Otago'),
(45, N'Southland'),
(45, N'Taranaki'),
(45, N'Tasman'),
(45, N'Waikato'),
(45, N'Wellington'),
(45, N'West Coast'),
(49, N'Saint-Denis'),
(50, N'Altaiskii krai'),
(50, N'Amurskaya obl.'),
(50, N'Arhangelskaya obl.'),
(50, N'Astrahanskaya obl.'),
(50, N'Bashkiriya obl.'),
(50, N'Belgorodskaya obl.'),
(50, N'Bryanskaya obl.'),
(50, N'Buryatiya'),
(50, N'Vladimirskaya obl.'),
(50, N'Volgogradskaya obl.'),
(50, N'Vologodskaya obl.'),
(50, N'Voronezhskaya obl.'),
(50, N'Nizhegorodskaya obl.'),
(50, N'Dagestan'),
(50, N'Evreiskaya obl.'),
(50, N'Ivanovskaya obl.'),
(50, N'Irkutskaya obl.'),
(50, N'Kabardino-Balkariya'),
(50, N'Kaliningradskaya obl.'),
(50, N'Tverskaya obl.'),
(50, N'Kalmykiya'),
(50, N'Kaluzhskaya obl.'),
(50, N'Kamchatskaya obl.'),
(50, N'Kareliya'),
(50, N'Kemerovskaya obl.'),
(50, N'Kirovskaya obl.'),
(50, N'Komi'),
(50, N'Kostromskaya obl.'),
(50, N'Krasnodarskii krai'),
(50, N'Krasnoyarskii krai'),
(50, N'Kurganskaya obl.'),
(50, N'Kurskaya obl.'),
(50, N'Lipetskaya obl.'),
(50, N'Magadanskaya obl.'),
(50, N'Marii El'),
(50, N'Mordoviya'),
(50, N'Moscow &amp; Moscow Region'),
(50, N'Murmanskaya obl.'),
(50, N'Novgorodskaya obl.'),
(50, N'Novosibirskaya obl.'),
(50, N'Omskaya obl.'),
(50, N'Orenburgskaya obl.'),
(50, N'Orlovskaya obl.'),
(50, N'Penzenskaya obl.'),
(50, N'Permskiy krai'),
(50, N'Primorskii krai'),
(50, N'Pskovskaya obl.'),
(50, N'Rostovskaya obl.'),
(50, N'Ryazanskaya obl.'),
(50, N'Samarskaya obl.'),
(50, N'Saint-Petersburg and Region'),
(50, N'Saratovskaya obl.'),
(50, N'Saha (Yakutiya)'),
(50, N'Sahalin'),
(50, N'Sverdlovskaya obl.'),
(50, N'Severnaya Osetiya'),
(50, N'Smolenskaya obl.'),
(50, N'Stavropolskii krai'),
(50, N'Tambovskaya obl.'),
(50, N'Tatarstan'),
(50, N'Tomskaya obl.'),
(50, N'Tulskaya obl.'),
(50, N'Tyumenskaya obl. i Hanty-Mansiiskii AO'),
(50, N'Udmurtiya'),
(50, N'Ulyanovskaya obl.'),
(50, N'Uralskaya obl.'),
(50, N'Habarovskii krai'),
(50, N'Chelyabinskaya obl.'),
(50, N'Checheno-Ingushetiya'),
(50, N'Chitinskaya obl.'),
(50, N'Chuvashiya'),
(50, N'Yaroslavskaya obl.'),
(51, N'Ahuachapán'),
(51, N'Cuscatlán'),
(51, N'La Libertad'),
(51, N'La Paz'),
(51, N'La Unión'),
(51, N'San Miguel'),
(51, N'San Salvador'),
(51, N'Santa Ana'),
(51, N'Sonsonate'),
(54, N'Paramaribo'),
(56, N'Gorno-Badakhshan Region'),
(56, N'Kuljabsk Region'),
(56, N'Kurgan-Tjube Region'),
(56, N'Sughd Region'),
(56, N'Tajikistan'),
(57, N'Ashgabat Region'),
(57, N'Krasnovodsk Region'),
(57, N'Mary Region'),
(57, N'Tashauz Region'),
(57, N'Chardzhou Region'),
(58, N'Grand Turk'),
(59, N'Bartin'),
(59, N'Bayburt'),
(59, N'Karabuk'),
(59, N'Adana'),
(59, N'Aydin'),
(59, N'Amasya'),
(59, N'Ankara'),
(59, N'Antalya'),
(59, N'Artvin'),
(59, N'Afion'),
(59, N'Balikesir'),
(59, N'Bilecik'),
(59, N'Bursa'),
(59, N'Gaziantep'),
(59, N'Denizli'),
(59, N'Izmir'),
(59, N'Isparta'),
(59, N'Icel'),
(59, N'Kayseri'),
(59, N'Kars'),
(59, N'Kodjaeli'),
(59, N'Konya'),
(59, N'Kirklareli'),
(59, N'Kutahya'),
(59, N'Malatya'),
(59, N'Manisa'),
(59, N'Sakarya'),
(59, N'Samsun'),
(59, N'Sivas'),
(59, N'Istanbul'),
(59, N'Trabzon'),
(59, N'Corum'),
(59, N'Edirne'),
(59, N'Elazig'),
(59, N'Erzincan'),
(59, N'Erzurum'),
(59, N'Eskisehir'),
(60, N'Jinja'),
(60, N'Kampala'),
(61, N'Andijon Region'),
(61, N'Buxoro Region'),
(61, N'Jizzac Region'),
(61, N'Qaraqalpaqstan'),
(61, N'Qashqadaryo Region'),
(61, N'Navoiy Region'),
(61, N'Namangan Region'),
(61, N'Samarqand Region'),
(61, N'Surxondaryo Region'),
(61, N'Sirdaryo Region'),
(61, N'Tashkent Region'),
(61, N'Fergana Region'),
(61, N'Xorazm Region'),
(62, N'Vinnitskaya obl.'),
(62, N'Volynskaya obl.'),
(62, N'Dnepropetrovskaya obl.'),
(62, N'Donetskaya obl.'),
(62, N'Zhitomirskaya obl.'),
(62, N'Zakarpatskaya obl.'),
(62, N'Zaporozhskaya obl.'),
(62, N'Ivano-Frankovskaya obl.'),
(62, N'Kievskaya obl.'),
(62, N'Kirovogradskaya obl.'),
(62, N'Krymskaya obl.'),
(62, N'Luganskaya obl.'),
(62, N'Lvovskaya obl.'),
(62, N'Nikolaevskaya obl.'),
(62, N'Odesskaya obl.'),
(62, N'Poltavskaya obl.'),
(62, N'Rovenskaya obl.'),
(62, N'Sumskaya obl.'),
(62, N'Ternopolskaya obl.'),
(62, N'Harkovskaya obl.'),
(62, N'Hersonskaya obl.'),
(62, N'Hmelnitskaya obl.'),
(62, N'Cherkasskaya obl.'),
(62, N'Chernigovskaya obl.'),
(62, N'Chernovitskaya obl.'),
(68, N'Estoniya'),
(69, N'Cheju'),
(69, N'Chollabuk'),
(69, N'Chollanam'),
(69, N'Chungcheongbuk'),
(69, N'Chungcheongnam'),
(69, N'Incheon'),
(69, N'Kangweon'),
(69, N'Kwangju'),
(69, N'Kyeonggi'),
(69, N'Kyeongsangbuk'),
(69, N'Kyeongsangnam'),
(69, N'Pusan'),
(69, N'Seoul'),
(69, N'Taegu'),
(69, N'Taejeon'),
(69, N'Ulsan'),
(70, N'Aichi'),
(70, N'Akita'),
(70, N'Aomori'),
(70, N'Wakayama'),
(70, N'Gifu'),
(70, N'Gunma'),
(70, N'Ibaraki'),
(70, N'Iwate'),
(70, N'Ishikawa'),
(70, N'Kagawa'),
(70, N'Kagoshima'),
(70, N'Kanagawa'),
(70, N'Kyoto'),
(70, N'Kochi'),
(70, N'Kumamoto'),
(70, N'Mie'),
(70, N'Miyagi'),
(70, N'Miyazaki'),
(70, N'Nagano'),
(70, N'Nagasaki'),
(70, N'Nara'),
(70, N'Niigata'),
(70, N'Okayama'),
(70, N'Okinawa'),
(70, N'Osaka'),
(70, N'Saga'),
(70, N'Saitama'),
(70, N'Shiga'),
(70, N'Shizuoka'),
(70, N'Shimane'),
(70, N'Tiba'),
(70, N'Tokyo'),
(70, N'Tokushima'),
(70, N'Tochigi'),
(70, N'Tottori'),
(70, N'Toyama'),
(70, N'Fukui'),
(70, N'Fukuoka'),
(70, N'Fukushima'),
(70, N'Hiroshima'),
(70, N'Hokkaido'),
(70, N'Hyogo'),
(70, N'Yoshimi'),
(70, N'Yamagata'),
(70, N'Yamaguchi'),
(70, N'Yamanashi'),
(73, N'Hong Kong'),
(74, N'Indonesia'),
(75, N'Jordan'),
(76, N'Malaysia'),
(77, N'Singapore'),
(78, N'Taiwan'),
(30, N'Kazahstan'),
(62, N'Ukraina'),
(25, N'India'),
(23, N'Egypt'),
(106, N'Damascus'),
(131, N'Isle of Man'),
(30, N'Zapadno-Kazahstanskaya obl.'),
(50, N'Adygeya'),
(50, N'Hakasiya'),
(93, N'Dubai'),
(50, N'Chukotskii AO'),
(99, N'Beirut'),
(137, N'Tegucigalpa'),
(138, N'Santo Domingo'),
(139, N'Ulan Bator'),
(23, N'Sinai'),
(140, N'Baghdad'),
(140, N'Basra'),
(140, N'Mosul'),
(141, N'Johannesburg'),
(104, N'Morocco'),
(104, N'Tangier'),
(50, N'Yamalo-Nenetskii AO'),
(122, N'Tunisia'),
(92, N'Thailand'),
(117, N'Mozambique'),
(84, N'Korea'),
(87, N'Pakistan'),
(142, N'Aruba'),
(80, N'Bahamas'),
(69, N'South Korea'),
(132, N'Jamaica'),
(93, N'Sharjah'),
(93, N'Abu Dhabi'),
(24, N'Ramat Hagolan'),
(115, N'Nigeria'),
(64, N'Ain'),
(64, N'Haute-Savoie'),
(64, N'Aisne'),
(64, N'Allier'),
(64, N'Alpes-de-Haute-Provence'),
(64, N'Hautes-Alpes'),
(64, N'Alpes-Maritimes'),
(64, N'Ard&egrave;che'),
(64, N'Ardennes'),
(64, N'Ari&egrave;ge'),
(64, N'Aube'),
(64, N'Aude'),
(64, N'Aveyron'),
(64, N'Bouches-du-Rh&ocirc;ne'),
(64, N'Calvados'),
(64, N'Cantal'),
(64, N'Charente'),
(64, N'Charente Maritime'),
(64, N'Cher'),
(64, N'Corr&egrave;ze'),
(64, N'Dordogne'),
(64, N'Corse'),
(64, N'C&ocirc;te d&#039;Or'),
(64, N'Sa&ocirc;ne et Loire'),
(64, N'C&ocirc;tes d&#039;Armor'),
(64, N'Creuse'),
(64, N'Doubs'),
(64, N'Dr&ocirc;me'),
(64, N'Eure'),
(64, N'Eure-et-Loire'),
(64, N'Finist&egrave;re'),
(64, N'Gard'),
(64, N'Haute-Garonne'),
(64, N'Gers'),
(64, N'Gironde'),
(64, N'Hérault'),
(64, N'Ille et Vilaine'),
(64, N'Indre'),
(64, N'Indre-et-Loire'),
(64, N'Isère'),
(64, N'Jura'),
(64, N'Landes'),
(64, N'Loir-et-Cher'),
(64, N'Loire'),
(64, N'Rh&ocirc;ne'),
(64, N'Haute-Loire'),
(64, N'Loire Atlantique'),
(64, N'Loiret'),
(64, N'Lot'),
(64, N'Lot-et-Garonne'),
(64, N'Loz&egrave;re'),
(64, N'Maine et Loire'),
(64, N'Manche'),
(64, N'Marne'),
(64, N'Haute-Marne'),
(64, N'Mayenne'),
(64, N'Meurthe-et-Moselle'),
(64, N'Meuse'),
(64, N'Morbihan'),
(64, N'Moselle'),
(64, N'Ni&egrave;vre'),
(64, N'Nord'),
(64, N'Oise'),
(64, N'Orne'),
(64, N'Pas-de-Calais'),
(64, N'Puy-de-D&ocirc;me'),
(64, N'Pyrénées-Atlantiques'),
(64, N'Hautes-Pyrénées'),
(64, N'Pyrénées-Orientales'),
(64, N'Bas Rhin'),
(64, N'Haut Rhin'),
(64, N'Haute-Sa&ocirc;ne'),
(64, N'Sarthe'),
(64, N'Savoie'),
(64, N'Paris'),
(64, N'Seine-Maritime'),
(64, N'Seine-et-Marne'),
(64, N'Yvelines'),
(64, N'Deux-S&egrave;vres'),
(64, N'Somme'),
(64, N'Tarn'),
(64, N'Tarn-et-Garonne'),
(64, N'Var'),
(64, N'Vaucluse'),
(64, N'Vendée'),
(64, N'Vienne'),
(64, N'Haute-Vienne'),
(64, N'Vosges'),
(64, N'Yonne'),
(64, N'Territoire de Belfort'),
(64, N'Essonne'),
(64, N'Hauts-de-Seine'),
(64, N'Seine-Saint-Denis'),
(64, N'Val-de-Marne'),
(64, N'Val-d&#039;Oise'),
(29, N'Piemonte - Torino'),
(29, N'Piemonte - Alessandria'),
(29, N'Piemonte - Asti'),
(29, N'Piemonte - Biella'),
(29, N'Piemonte - Cuneo'),
(29, N'Piemonte - Novara'),
(29, N'Piemonte - Verbania'),
(29, N'Piemonte - Vercelli'),
(29, N'Valle d&#039;Aosta - Aosta'),
(29, N'Lombardia - Milano'),
(29, N'Lombardia - Bergamo'),
(29, N'Lombardia - Brescia'),
(29, N'Lombardia - Como'),
(29, N'Lombardia - Cremona'),
(29, N'Lombardia - Lecco'),
(29, N'Lombardia - Lodi'),
(29, N'Lombardia - Mantova'),
(29, N'Lombardia - Pavia'),
(29, N'Lombardia - Sondrio'),
(29, N'Lombardia - Varese'),
(29, N'Trentino Alto Adige - Trento'),
(29, N'Trentino Alto Adige - Bolzano'),
(29, N'Veneto - Venezia'),
(29, N'Veneto - Belluno'),
(29, N'Veneto - Padova'),
(29, N'Veneto - Rovigo'),
(29, N'Veneto - Treviso'),
(29, N'Veneto - Verona'),
(29, N'Veneto - Vicenza'),
(29, N'Friuli Venezia Giulia - Trieste'),
(29, N'Friuli Venezia Giulia - Gorizia'),
(29, N'Friuli Venezia Giulia - Pordenone'),
(29, N'Friuli Venezia Giulia - Udine'),
(29, N'Liguria - Genova'),
(29, N'Liguria - Imperia'),
(29, N'Liguria - La Spezia'),
(29, N'Liguria - Savona'),
(29, N'Emilia Romagna - Bologna'),
(29, N'Emilia Romagna - Ferrara'),
(29, N'Emilia Romagna - Forlì-Cesena'),
(29, N'Emilia Romagna - Modena'),
(29, N'Emilia Romagna - Parma'),
(29, N'Emilia Romagna - Piacenza'),
(29, N'Emilia Romagna - Ravenna'),
(29, N'Emilia Romagna - Reggio Emilia'),
(29, N'Emilia Romagna - Rimini'),
(29, N'Toscana - Firenze'),
(29, N'Toscana - Arezzo'),
(29, N'Toscana - Grosseto'),
(29, N'Toscana - Livorno'),
(29, N'Toscana - Lucca'),
(29, N'Toscana - Massa Carrara'),
(29, N'Toscana - Pisa'),
(29, N'Toscana - Pistoia'),
(29, N'Toscana - Prato'),
(29, N'Toscana - Siena'),
(29, N'Umbria - Perugia'),
(29, N'Umbria - Terni'),
(29, N'Marche - Ancona'),
(29, N'Marche - Ascoli Piceno'),
(29, N'Marche - Macerata'),
(29, N'Marche - Pesaro - Urbino'),
(29, N'Lazio - Roma'),
(29, N'Lazio - Frosinone'),
(29, N'Lazio - Latina'),
(29, N'Lazio - Rieti'),
(29, N'Lazio - Viterbo'),
(29, N'Abruzzo - L´Aquila'),
(29, N'Abruzzo - Chieti'),
(29, N'Abruzzo - Pescara'),
(29, N'Abruzzo - Teramo'),
(29, N'Molise - Campobasso'),
(29, N'Molise - Isernia'),
(29, N'Campania - Napoli'),
(29, N'Campania - Avellino'),
(29, N'Campania - Benevento'),
(29, N'Campania - Caserta'),
(29, N'Campania - Salerno'),
(29, N'Puglia - Bari'),
(29, N'Puglia - Brindisi'),
(29, N'Puglia - Foggia'),
(29, N'Puglia - Lecce'),
(29, N'Puglia - Taranto'),
(29, N'Basilicata - Potenza'),
(29, N'Basilicata - Matera'),
(29, N'Calabria - Catanzaro'),
(29, N'Calabria - Cosenza'),
(29, N'Calabria - Crotone'),
(29, N'Calabria - Reggio Calabria'),
(29, N'Calabria - Vibo Valentia'),
(29, N'Sicilia - Palermo'),
(29, N'Sicilia - Agrigento'),
(29, N'Sicilia - Caltanissetta'),
(29, N'Sicilia - Catania'),
(29, N'Sicilia - Enna'),
(29, N'Sicilia - Messina'),
(29, N'Sicilia - Ragusa'),
(29, N'Sicilia - Siracusa'),
(29, N'Sicilia - Trapani'),
(29, N'Sardegna - Cagliari'),
(29, N'Sardegna - Nuoro'),
(29, N'Sardegna - Oristano'),
(29, N'Sardegna - Sassari'),
(28, N'Las Palmas'),
(28, N'Soria'),
(28, N'Palencia'),
(28, N'Zamora'),
(28, N'Cádiz'),
(28, N'Navarra'),
(28, N'Ourense'),
(28, N'Segovia'),
(28, N'Guip&uacute;zcoa'),
(28, N'Ciudad Real'),
(28, N'Vizcaya'),
(28, N'álava'),
(28, N'A Coruña'),
(28, N'Cantabria'),
(28, N'Almería'),
(28, N'Zaragoza'),
(28, N'Santa Cruz de Tenerife'),
(28, N'Cáceres'),
(28, N'Guadalajara'),
(28, N'ávila'),
(28, N'Toledo'),
(28, N'Castellón'),
(28, N'Tarragona'),
(28, N'Lugo'),
(28, N'La Rioja'),
(28, N'Ceuta'),
(28, N'Murcia'),
(28, N'Salamanca'),
(28, N'Valladolid'),
(28, N'Jaén'),
(28, N'Girona'),
(28, N'Granada'),
(28, N'Alacant'),
(28, N'Córdoba'),
(28, N'Albacete'),
(28, N'Cuenca'),
(28, N'Pontevedra'),
(28, N'Teruel'),
(28, N'Melilla'),
(28, N'Barcelona'),
(28, N'Badajoz'),
(28, N'Madrid'),
(28, N'Sevilla'),
(28, N'Val&egrave;ncia'),
(28, N'Huelva'),
(28, N'Lleida'),
(28, N'León'),
(28, N'Illes Balears'),
(28, N'Burgos'),
(28, N'Huesca'),
(28, N'Asturias'),
(28, N'Málaga'),
(144, N'Afghanistan'),
(210, N'Niger'),
(133, N'Mali'),
(156, N'Burkina Faso'),
(136, N'Togo'),
(151, N'Benin'),
(119, N'Angola'),
(102, N'Namibia'),
(100, N'Botswana'),
(134, N'Madagascar'),
(202, N'Mauritius'),
(196, N'Laos'),
(158, N'Cambodia'),
(90, N'Philippines'),
(88, N'Papua New Guinea'),
(228, N'Solomon Islands'),
(240, N'Vanuatu'),
(176, N'Fiji'),
(223, N'Samoa'),
(206, N'Nauru'),
(168, N'Cote D&#039;Ivoire'),
(198, N'Liberia'),
(187, N'Guinea'),
(189, N'Guyana'),
(98, N'Algeria'),
(147, N'Antigua and Barbuda'),
(127, N'Bahrain'),
(149, N'Bangladesh'),
(128, N'Barbados'),
(152, N'Bhutan'),
(155, N'Brunei'),
(157, N'Burundi'),
(159, N'Cape Verde'),
(130, N'Chad'),
(164, N'Comoros'),
(112, N'Congo (Brazzaville)'),
(169, N'Djibouti'),
(171, N'East Timor'),
(173, N'Eritrea'),
(121, N'Ethiopia'),
(180, N'Gabon'),
(181, N'Gambia'),
(105, N'Ghana'),
(197, N'Lesotho'),
(125, N'Malawi'),
(200, N'Maldives'),
(205, N'Myanmar (Burma)'),
(107, N'Nepal'),
(213, N'Oman'),
(217, N'Rwanda'),
(91, N'Saudi Arabia'),
(120, N'Sri Lanka'),
(232, N'Sudan'),
(234, N'Swaziland'),
(101, N'Tanzania'),
(236, N'Tonga'),
(239, N'Tuvalu'),
(242, N'Western Sahara'),
(243, N'Yemen'),
(116, N'Zambia'),
(96, N'Zimbabwe'),
(66, N'Aargau'),
(66, N'Appenzell Innerrhoden'),
(66, N'Appenzell Ausserrhoden'),
(66, N'Bern'),
(66, N'Basel-Landschaft'),
(66, N'Basel-Stadt'),
(66, N'Fribourg'),
(66, N'Gen&egrave;ve'),
(66, N'Glarus'),
(66, N'Graubünden'),
(66, N'Jura'),
(66, N'Luzern'),
(66, N'Neuch&acirc;tel'),
(66, N'Nidwalden'),
(66, N'Obwalden'),
(66, N'Sankt Gallen'),
(66, N'Schaffhausen'),
(66, N'Solothurn'),
(66, N'Schwyz'),
(66, N'Thurgau'),
(66, N'Ticino'),
(66, N'Uri'),
(66, N'Vaud'),
(66, N'Valais'),
(66, N'Zug'),
(66, N'Zürich'),
(48, N'Aveiro'),
(48, N'Beja'),
(48, N'Braga'),
(48, N'Braganca'),
(48, N'Castelo Branco'),
(48, N'Coimbra'),
(48, N'Evora'),
(48, N'Faro'),
(48, N'Madeira'),
(48, N'Guarda'),
(48, N'Leiria'),
(48, N'Lisboa'),
(48, N'Portalegre'),
(48, N'Porto'),
(48, N'Santarem'),
(48, N'Setubal'),
(48, N'Viana do Castelo'),
(48, N'Vila Real'),
(48, N'Viseu'),
(48, N'Azores'),
(55, N'Armed Forces Americas'),
(55, N'Armed Forces Europe'),
(55, N'Alaska'),
(55, N'Alabama'),
(55, N'Armed Forces Pacific'),
(55, N'Arkansas'),
(55, N'American Samoa'),
(55, N'Arizona'),
(55, N'California'),
(55, N'Colorado'),
(55, N'Connecticut'),
(55, N'District of Columbia'),
(55, N'Delaware'),
(55, N'Florida'),
(55, N'Federated States of Micronesia'),
(55, N'Georgia'),
(55, N'Hawaii'),
(55, N'Iowa'),
(55, N'Idaho'),
(55, N'Illinois'),
(55, N'Indiana'),
(55, N'Kansas'),
(55, N'Kentucky'),
(55, N'Louisiana'),
(55, N'Massachusetts')
GO

INSERT INTO Regiones (PaisId, Nombre) VALUES
(55, N'Maryland'),
(55, N'Maine'),
(55, N'Marshall Islands'),
(55, N'Michigan'),
(55, N'Minnesota'),
(55, N'Missouri'),
(55, N'Northern Mariana Islands'),
(55, N'Mississippi'),
(55, N'Montana'),
(55, N'North Carolina'),
(55, N'North Dakota'),
(55, N'Nebraska'),
(55, N'New Hampshire'),
(55, N'New Jersey'),
(55, N'New Mexico'),
(55, N'Nevada'),
(55, N'New York'),
(55, N'Ohio'),
(55, N'Oklahoma'),
(55, N'Oregon'),
(55, N'Pennsylvania'),
(246, N'Puerto Rico'),
(55, N'Palau'),
(55, N'Rhode Island'),
(55, N'South Carolina'),
(55, N'South Dakota'),
(55, N'Tennessee'),
(55, N'Texas'),
(55, N'Utah'),
(55, N'Virginia'),
(55, N'Virgin Islands'),
(55, N'Vermont'),
(55, N'Washington'),
(55, N'West Virginia'),
(55, N'Wisconsin'),
(55, N'Wyoming'),
(94, N'Greenland'),
(18, N'Brandenburg'),
(18, N'Baden-Württemberg'),
(18, N'Bayern'),
(18, N'Hessen'),
(18, N'Hamburg'),
(18, N'Mecklenburg-Vorpommern'),
(18, N'Niedersachsen'),
(18, N'Nordrhein-Westfalen'),
(18, N'Rheinland-Pfalz'),
(18, N'Schleswig-Holstein'),
(18, N'Sachsen'),
(18, N'Sachsen-Anhalt'),
(18, N'Thüringen'),
(18, N'Berlin'),
(18, N'Bremen'),
(18, N'Saarland'),
(13, N'Scotland North'),
(13, N'England - East'),
(13, N'England - West Midlands'),
(13, N'England - South West'),
(13, N'England - North West'),
(13, N'England - Yorks &amp; Humber'),
(13, N'England - South East'),
(13, N'England - London'),
(13, N'Northern Ireland'),
(13, N'England - North East'),
(13, N'Wales South'),
(13, N'Wales North'),
(13, N'England - East Midlands'),
(13, N'Scotland Central'),
(13, N'Scotland South'),
(13, N'Channel Islands'),
(13, N'Isle of Man'),
(2, N'Burgenland'),
(2, N'Kärnten'),
(2, N'Niederösterreich'),
(2, N'Oberösterreich'),
(2, N'Salzburg'),
(2, N'Steiermark'),
(2, N'Tirol'),
(2, N'Vorarlberg'),
(2, N'Wien'),
(9, N'Bruxelles'),
(9, N'West-Vlaanderen'),
(9, N'Oost-Vlaanderen'),
(9, N'Limburg'),
(9, N'Vlaams Brabant'),
(9, N'Antwerpen'),
(9, N'LiÄge'),
(9, N'Namur'),
(9, N'Hainaut'),
(9, N'Luxembourg'),
(9, N'Brabant Wallon'),
(67, N'Blekinge Lan'),
(67, N'Gavleborgs Lan'),
(67, N'Gotlands Lan'),
(67, N'Hallands Lan'),
(67, N'Jamtlands Lan'),
(67, N'Jonkopings Lan'),
(67, N'Kalmar Lan'),
(67, N'Dalarnas Lan'),
(67, N'Kronobergs Lan'),
(67, N'Norrbottens Lan'),
(67, N'Orebro Lan'),
(67, N'Ostergotlands Lan'),
(67, N'Sodermanlands Lan'),
(67, N'Uppsala Lan'),
(67, N'Varmlands Lan'),
(67, N'Vasterbottens Lan'),
(67, N'Vasternorrlands Lan'),
(67, N'Vastmanlands Lan'),
(67, N'Stockholms Lan'),
(67, N'Skane Lan'),
(67, N'Vastra Gotaland'),
(46, N'Akershus'),
(46, N'Aust-Agder'),
(46, N'Buskerud'),
(46, N'Finnmark'),
(46, N'Hedmark'),
(46, N'Hordaland'),
(46, N'More og Romsdal'),
(46, N'Nordland'),
(46, N'Nord-Trondelag'),
(46, N'Oppland'),
(46, N'Oslo'),
(46, N'Ostfold'),
(46, N'Rogaland'),
(46, N'Sogn og Fjordane'),
(46, N'Sor-Trondelag'),
(46, N'Telemark'),
(46, N'Troms'),
(46, N'Vest-Agder'),
(46, N'Vestfold'),
(63, N'Ðland'),
(63, N'Lapland'),
(63, N'Oulu'),
(63, N'Southern Finland'),
(63, N'Eastern Finland'),
(63, N'Western Finland'),
(22, N'Arhus'),
(22, N'Bornholm'),
(22, N'Frederiksborg'),
(22, N'Fyn'),
(22, N'Kobenhavn'),
(22, N'Staden Kobenhavn'),
(22, N'Nordjylland'),
(22, N'Ribe'),
(22, N'Ringkobing'),
(22, N'Roskilde'),
(22, N'Sonderjylland'),
(22, N'Storstrom'),
(22, N'Vejle'),
(22, N'Vestsjalland'),
(22, N'Viborg'),
(65, N'Hlavni Mesto Praha'),
(65, N'Jihomoravsky Kraj'),
(65, N'Jihocesky Kraj'),
(65, N'Vysocina'),
(65, N'Karlovarsky Kraj'),
(65, N'Kralovehradecky Kraj'),
(65, N'Liberecky Kraj'),
(65, N'Olomoucky Kraj'),
(65, N'Moravskoslezsky Kraj'),
(65, N'Pardubicky Kraj'),
(65, N'Plzensky Kraj'),
(65, N'Stredocesky Kraj'),
(65, N'Ustecky Kraj'),
(65, N'Zlinsky Kraj'),
(114, N'Berat'),
(114, N'Diber'),
(114, N'Durres'),
(114, N'Elbasan'),
(114, N'Fier'),
(114, N'Gjirokaster'),
(114, N'Korce'),
(114, N'Kukes'),
(114, N'Lezhe'),
(114, N'Shkoder'),
(114, N'Tirane'),
(114, N'Vlore'),
(145, N'Canillo'),
(145, N'Encamp'),
(145, N'La Massana'),
(145, N'Ordino'),
(145, N'Sant Julia de Loria'),
(145, N'Andorra la Vella'),
(145, N'Escaldes-Engordany'),
(6, N'Aragatsotn'),
(6, N'Ararat'),
(6, N'Armavir'),
(6, N'Geghark&#039;unik&#039;'),
(6, N'Kotayk&#039;'),
(6, N'Lorri'),
(6, N'Shirak'),
(6, N'Syunik&#039;'),
(6, N'Tavush'),
(6, N'Vayots&#039; Dzor'),
(6, N'Yerevan'),
(79, N'Federation of Bosnia and Herzegovina'),
(79, N'Republika Srpska'),
(11, N'Mikhaylovgrad'),
(11, N'Blagoevgrad'),
(11, N'Burgas'),
(11, N'Dobrich'),
(11, N'Gabrovo'),
(11, N'Grad Sofiya'),
(11, N'Khaskovo'),
(11, N'Kurdzhali'),
(11, N'Kyustendil'),
(11, N'Lovech'),
(11, N'Montana'),
(11, N'Pazardzhik'),
(11, N'Pernik'),
(11, N'Pleven'),
(11, N'Plovdiv'),
(11, N'Razgrad'),
(11, N'Ruse'),
(11, N'Shumen'),
(11, N'Silistra'),
(11, N'Sliven'),
(11, N'Smolyan'),
(11, N'Sofiya'),
(11, N'Stara Zagora'),
(11, N'Turgovishte'),
(11, N'Varna'),
(11, N'Veliko Turnovo'),
(11, N'Vidin'),
(11, N'Vratsa'),
(11, N'Yambol'),
(71, N'Bjelovarsko-Bilogorska'),
(71, N'Brodsko-Posavska'),
(71, N'Dubrovacko-Neretvanska'),
(71, N'Istarska'),
(71, N'Karlovacka'),
(71, N'Koprivnicko-Krizevacka'),
(71, N'Krapinsko-Zagorska'),
(71, N'Licko-Senjska'),
(71, N'Medimurska'),
(71, N'Osjecko-Baranjska'),
(71, N'Pozesko-Slavonska'),
(71, N'Primorsko-Goranska'),
(71, N'Sibensko-Kninska'),
(71, N'Sisacko-Moslavacka'),
(71, N'Splitsko-Dalmatinska'),
(71, N'Varazdinska'),
(71, N'Viroviticko-Podravska'),
(71, N'Vukovarsko-Srijemska'),
(71, N'Zadarska'),
(71, N'Zagrebacka'),
(71, N'Grad Zagreb'),
(143, N'Gibraltar'),
(20, N'Evros'),
(20, N'Rodhopi'),
(20, N'Xanthi'),
(20, N'Drama'),
(20, N'Serrai'),
(20, N'Kilkis'),
(20, N'Pella'),
(20, N'Florina'),
(20, N'Kastoria'),
(20, N'Grevena'),
(20, N'Kozani'),
(20, N'Imathia'),
(20, N'Thessaloniki'),
(20, N'Kavala'),
(20, N'Khalkidhiki'),
(20, N'Pieria'),
(20, N'Ioannina'),
(20, N'Thesprotia'),
(20, N'Preveza'),
(20, N'Arta'),
(20, N'Larisa'),
(20, N'Trikala'),
(20, N'Kardhitsa'),
(20, N'Magnisia'),
(20, N'Kerkira'),
(20, N'Levkas'),
(20, N'Kefallinia'),
(20, N'Zakinthos'),
(20, N'Fthiotis'),
(20, N'Evritania'),
(20, N'Aitolia kai Akarnania'),
(20, N'Fokis'),
(20, N'Voiotia'),
(20, N'Evvoia'),
(20, N'Attiki'),
(20, N'Argolis'),
(20, N'Korinthia'),
(20, N'Akhaia'),
(20, N'Ilia'),
(20, N'Messinia'),
(20, N'Arkadhia'),
(20, N'Lakonia'),
(20, N'Khania'),
(20, N'Rethimni'),
(20, N'Iraklion'),
(20, N'Lasithi'),
(20, N'Dhodhekanisos'),
(20, N'Samos'),
(20, N'Kikladhes'),
(20, N'Khios'),
(20, N'Lesvos'),
(14, N'Bacs-Kiskun'),
(14, N'Baranya'),
(14, N'Bekes'),
(14, N'Borsod-Abauj-Zemplen'),
(14, N'Budapest'),
(14, N'Csongrad'),
(14, N'Debrecen'),
(14, N'Fejer'),
(14, N'Gyor-Moson-Sopron'),
(14, N'Hajdu-Bihar'),
(14, N'Heves'),
(14, N'Komarom-Esztergom'),
(14, N'Miskolc'),
(14, N'Nograd'),
(14, N'Pecs'),
(14, N'Pest'),
(14, N'Somogy'),
(14, N'Szabolcs-Szatmar-Bereg'),
(14, N'Szeged'),
(14, N'Jasz-Nagykun-Szolnok'),
(14, N'Tolna'),
(14, N'Vas'),
(14, N'Veszprem'),
(14, N'Zala'),
(14, N'Gyor'),
(14, N'Veszprem'),
(126, N'Balzers'),
(126, N'Eschen'),
(126, N'Gamprin'),
(126, N'Mauren'),
(126, N'Planken'),
(126, N'Ruggell'),
(126, N'Schaan'),
(126, N'Schellenberg'),
(126, N'Triesen'),
(126, N'Triesenberg'),
(126, N'Vaduz'),
(41, N'Diekirch'),
(41, N'Grevenmacher'),
(41, N'Luxembourg'),
(85, N'Aracinovo'),
(85, N'Bac'),
(85, N'Belcista'),
(85, N'Berovo'),
(85, N'Bistrica'),
(85, N'Bitola'),
(85, N'Blatec'),
(85, N'Bogdanci'),
(85, N'Bogomila'),
(85, N'Bogovinje'),
(85, N'Bosilovo'),
(85, N'Cair'),
(85, N'Capari'),
(85, N'Caska'),
(85, N'Cegrane'),
(85, N'Centar Zupa'),
(85, N'Debar'),
(85, N'Delcevo'),
(85, N'Demir Hisar'),
(85, N'Demir Kapija'),
(85, N'Dorce Petrov'),
(85, N'Gazi Baba'),
(85, N'Gevgelija'),
(85, N'Gostivar'),
(85, N'Gradsko'),
(85, N'Jegunovce'),
(85, N'Kamenjane'),
(85, N'Karpos'),
(85, N'Kavadarci'),
(85, N'Kicevo'),
(85, N'Kisela Voda'),
(85, N'Klecevce'),
(85, N'Kocani'),
(85, N'Kondovo'),
(85, N'Kratovo'),
(85, N'Krivogastani'),
(85, N'Krusevo'),
(85, N'Kumanovo'),
(85, N'Labunista'),
(85, N'Lipkovo'),
(85, N'Makedonska Kamenica'),
(85, N'Makedonski Brod'),
(85, N'Murtino'),
(85, N'Negotino'),
(85, N'Novo Selo'),
(85, N'Ohrid'),
(85, N'Orizari'),
(85, N'Petrovec'),
(85, N'Prilep'),
(85, N'Probistip'),
(85, N'Radovis'),
(85, N'Resen'),
(85, N'Rosoman'),
(85, N'Saraj'),
(85, N'Srbinovo'),
(85, N'Star Dojran'),
(85, N'Stip'),
(85, N'Struga'),
(85, N'Strumica'),
(85, N'Studenicani'),
(85, N'Suto Orizari'),
(85, N'Sveti Nikole'),
(85, N'Tearce'),
(85, N'Tetovo'),
(85, N'Valandovo'),
(85, N'Veles'),
(85, N'Vevcani'),
(85, N'Vinica'),
(85, N'Vrapciste'),
(85, N'Zelino'),
(85, N'Zrnovci'),
(86, N'Malta'),
(44, N'La Condamine'),
(44, N'Monaco'),
(44, N'Monte-Carlo'),
(47, N'Biala Podlaska'),
(47, N'Bialystok'),
(47, N'Bielsko'),
(47, N'Bydgoszcz'),
(47, N'Chelm'),
(47, N'Ciechanow'),
(47, N'Czestochowa'),
(47, N'Elblag'),
(47, N'Gdansk'),
(47, N'Gorzow'),
(47, N'Jelenia Gora'),
(47, N'Kalisz'),
(47, N'Katowice'),
(47, N'Kielce'),
(47, N'Konin'),
(47, N'Koszalin'),
(47, N'Krakow'),
(47, N'Krosno'),
(47, N'Legnica'),
(47, N'Leszno'),
(47, N'Lodz'),
(47, N'Lomza'),
(47, N'Lublin'),
(47, N'Nowy Sacz'),
(47, N'Olsztyn'),
(47, N'Opole'),
(47, N'Ostroleka'),
(47, N'Pila'),
(47, N'Piotrkow'),
(47, N'Plock'),
(47, N'Poznan'),
(47, N'Przemysl'),
(47, N'Radom'),
(47, N'Rzeszow'),
(47, N'Siedlce'),
(47, N'Sieradz'),
(47, N'Skierniewice'),
(47, N'Slupsk'),
(47, N'Suwalki'),
(47, N'Tarnobrzeg'),
(47, N'Tarnow'),
(47, N'Torun'),
(47, N'Walbrzych'),
(47, N'Warszawa'),
(47, N'Wloclawek'),
(47, N'Wroclaw'),
(47, N'Zamosc'),
(47, N'Zielona Gora'),
(47, N'Dolnoslaskie'),
(47, N'Kujawsko-Pomorskie'),
(47, N'Lodzkie'),
(47, N'Lubelskie'),
(47, N'Lubuskie'),
(47, N'Malopolskie'),
(47, N'Mazowieckie'),
(47, N'Opolskie'),
(47, N'Podkarpackie'),
(47, N'Podlaskie'),
(47, N'Pomorskie'),
(47, N'Slaskie'),
(47, N'Swietokrzyskie'),
(47, N'Warminsko-Mazurskie'),
(47, N'Wielkopolskie'),
(47, N'Zachodniopomorskie'),
(72, N'Alba'),
(72, N'Arad'),
(72, N'Arges'),
(72, N'Bacau'),
(72, N'Bihor'),
(72, N'Bistrita-Nasaud'),
(72, N'Botosani'),
(72, N'Braila'),
(72, N'Brasov'),
(72, N'Bucuresti'),
(72, N'Buzau'),
(72, N'Caras-Severin'),
(72, N'Cluj'),
(72, N'Constanta'),
(72, N'Covasna'),
(72, N'Dambovita'),
(72, N'Dolj'),
(72, N'Galati'),
(72, N'Gorj'),
(72, N'Harghita')
GO

INSERT INTO Regiones (PaisId, Nombre) VALUES
(72, N'Hunedoara'),
(72, N'Ialomita'),
(72, N'Iasi'),
(72, N'Maramures'),
(72, N'Mehedinti'),
(72, N'Mures'),
(72, N'Neamt'),
(72, N'Olt'),
(72, N'Prahova'),
(72, N'Salaj'),
(72, N'Satu Mare'),
(72, N'Sibiu'),
(72, N'Suceava'),
(72, N'Teleorman'),
(72, N'Timis'),
(72, N'Tulcea'),
(72, N'Vaslui'),
(72, N'Valcea'),
(72, N'Vrancea'),
(72, N'Calarasi'),
(72, N'Giurgiu'),
(224, N'Acquaviva'),
(224, N'Chiesanuova'),
(224, N'Domagnano'),
(224, N'Faetano'),
(224, N'Fiorentino'),
(224, N'Borgo Maggiore'),
(224, N'San Marino'),
(224, N'Monte Giardino'),
(224, N'Serravalle'),
(52, N'Banska Bystrica'),
(52, N'Bratislava'),
(52, N'Kosice'),
(52, N'Nitra'),
(52, N'Presov'),
(52, N'Trencin'),
(52, N'Trnava'),
(52, N'Zilina'),
(53, N'Beltinci'),
(53, N'Bohinj'),
(53, N'Borovnica'),
(53, N'Bovec'),
(53, N'Brda'),
(53, N'Brezice'),
(53, N'Brezovica'),
(53, N'Cerklje na Gorenjskem'),
(53, N'Cerkno'),
(53, N'Crna na Koroskem'),
(53, N'Crnomelj'),
(53, N'Divaca'),
(53, N'Dobrepolje'),
(53, N'Dol pri Ljubljani'),
(53, N'Duplek'),
(53, N'Gornji Grad'),
(53, N'Hrastnik'),
(53, N'Hrpelje-Kozina'),
(53, N'Idrija'),
(53, N'Ig'),
(53, N'Ilirska Bistrica'),
(53, N'Ivancna Gorica'),
(53, N'Komen'),
(53, N'Koper-Capodistria'),
(53, N'Kozje'),
(53, N'Kranj'),
(53, N'Kranjska Gora'),
(53, N'Krsko'),
(53, N'Lasko'),
(53, N'Ljubljana'),
(53, N'Ljubno'),
(53, N'Logatec'),
(53, N'Medvode'),
(53, N'Menges'),
(53, N'Mezica'),
(53, N'Moravce'),
(53, N'Mozirje'),
(53, N'Murska Sobota'),
(53, N'Nova Gorica'),
(53, N'Ormoz'),
(53, N'Pesnica'),
(53, N'Postojna'),
(53, N'Radece'),
(53, N'Radenci'),
(53, N'Radovljica'),
(53, N'Rogaska Slatina'),
(53, N'Sencur'),
(53, N'Sentilj'),
(53, N'Sevnica'),
(53, N'Sezana'),
(53, N'Skofja Loka'),
(53, N'Slovenj Gradec'),
(53, N'Slovenske Konjice'),
(53, N'Smarje pri Jelsah'),
(53, N'Tolmin'),
(53, N'Trbovlje'),
(53, N'Trzic'),
(53, N'Velenje'),
(53, N'Vipava'),
(53, N'Vrhnika'),
(53, N'Vuzenica'),
(53, N'Zagorje ob Savi'),
(53, N'Zelezniki'),
(53, N'Ziri'),
(53, N'Zrece'),
(53, N'Domzale'),
(53, N'Jesenice'),
(53, N'Kamnik'),
(53, N'Kocevje'),
(53, N'Lenart'),
(53, N'Litija'),
(53, N'Ljutomer'),
(53, N'Maribor'),
(53, N'Novo Mesto'),
(53, N'Piran'),
(53, N'Preddvor'),
(53, N'Ptuj'),
(53, N'Ribnica'),
(53, N'Sentjur pri Celju'),
(53, N'Slovenska Bistrica'),
(53, N'Videm'),
(53, N'Zalec'),
(109, N'Seychelles'),
(108, N'Mauritania'),
(135, N'Senegal'),
(154, N'Road Town'),
(165, N'Congo'),
(166, N'Avarua'),
(172, N'Malabo'),
(175, N'Torshavn'),
(178, N'Papeete'),
(184, N'St George&#039;s'),
(186, N'St Peter Port'),
(188, N'Bissau'),
(193, N'Saint Helier'),
(201, N'Fort-de-France'),
(207, N'Willemstad'),
(208, N'Noumea'),
(212, N'Kingston'),
(215, N'Adamstown'),
(216, N'Doha'),
(218, N'Jamestown'),
(219, N'Basseterre'),
(220, N'Castries'),
(221, N'Saint Pierre'),
(222, N'Kingstown'),
(225, N'San Tome'),
(226, N'Belgrade'),
(227, N'Freetown'),
(229, N'Mogadishu'),
(235, N'Fakaofo'),
(237, N'Port of Spain'),
(241, N'Mata-Utu'),
(89, N'Amazonas'),
(89, N'Ancash'),
(89, N'Apurímac'),
(89, N'Arequipa'),
(89, N'Ayacucho'),
(89, N'Cajamarca'),
(89, N'Callao'),
(89, N'Cusco'),
(89, N'Huancavelica'),
(89, N'Huánuco'),
(89, N'Ica'),
(89, N'Junín'),
(89, N'La Libertad'),
(89, N'Lambayeque'),
(89, N'Lima'),
(89, N'Loreto'),
(89, N'Madre de Dios'),
(89, N'Moquegua'),
(89, N'Pasco'),
(89, N'Piura'),
(89, N'Puno'),
(89, N'San Martín'),
(89, N'Tacna'),
(89, N'Tumbes'),
(89, N'Ucayali'),
(110, N'Alto Paraná'),
(110, N'Amambay'),
(110, N'Boquerón'),
(110, N'Caaguaz&uacute;'),
(110, N'Caazapá'),
(110, N'Central'),
(110, N'Concepción'),
(110, N'Cordillera'),
(110, N'Guairá'),
(110, N'Itap&uacute;a'),
(110, N'Misiones'),
(110, N'Neembuc&uacute;'),
(110, N'Paraguarí'),
(110, N'Presidente Hayes'),
(110, N'San Pedro'),
(110, N'Alto Paraguay'),
(110, N'Canindey&uacute;'),
(110, N'Chaco'),
(111, N'Artigas'),
(111, N'Canelones'),
(111, N'Cerro Largo'),
(111, N'Colonia'),
(111, N'Durazno'),
(111, N'Flores'),
(111, N'Florida'),
(111, N'Lavalleja'),
(111, N'Maldonado'),
(111, N'Montevideo'),
(111, N'Paysand&uacute;'),
(111, N'Río Negro'),
(111, N'Rivera'),
(111, N'Rocha'),
(111, N'Salto'),
(111, N'San José'),
(111, N'Soriano'),
(111, N'Tacuarembó'),
(111, N'Treinta y Tres'),
(81, N'Región de Tarapacá'),
(81, N'Región de Antofagasta'),
(81, N'Región de Atacama'),
(81, N'Región de Coquimbo'),
(81, N'Región de Valparaíso'),
(81, N'Región del Libertador General Bernardo O&#039;Higgins'),
(81, N'Región del Maule'),
(81, N'Región del Bío Bío'),
(81, N'Región de La Araucanía'),
(81, N'Región de Los Lagos'),
(81, N'Región Aisén del General Carlos Ibáñez del Campo'),
(81, N'Región de Magallanes y de la Antártica Chilena'),
(81, N'Región Metropolitana de Santiago'),
(185, N'Alta Verapaz'),
(185, N'Baja Verapaz'),
(185, N'Chimaltenango'),
(185, N'Chiquimula'),
(185, N'El Progreso'),
(185, N'Escuintla'),
(185, N'Guatemala'),
(185, N'Huehuetenango'),
(185, N'Izabal'),
(185, N'Jalapa'),
(185, N'Jutiapa'),
(185, N'Petén'),
(185, N'Quetzaltenango'),
(185, N'Quiché'),
(185, N'Retalhuleu'),
(185, N'Sacatepéquez'),
(185, N'San Marcos'),
(185, N'Santa Rosa'),
(185, N'Sololá'),
(185, N'Suchitepequez'),
(185, N'Totonicapán'),
(185, N'Zacapa'),
(82, N'Amazonas'),
(82, N'Antioquia'),
(82, N'Arauca'),
(82, N'Atlántico'),
(82, N'Caquetá'),
(82, N'Cauca'),
(82, N'César'),
(82, N'Chocó'),
(82, N'Córdoba'),
(82, N'Guaviare'),
(82, N'Guainía'),
(82, N'Huila'),
(82, N'La Guajira'),
(82, N'Meta'),
(82, N'Narino'),
(82, N'Norte de Santander'),
(82, N'Putumayo'),
(82, N'Quindío'),
(82, N'Risaralda'),
(82, N'San Andrés y Providencia'),
(82, N'Santander'),
(82, N'Sucre'),
(82, N'Tolima'),
(82, N'Valle del Cauca'),
(82, N'Vaupés'),
(82, N'Vichada'),
(82, N'Casanare'),
(82, N'Cundinamarca'),
(82, N'Distrito Especial'),
(82, N'Caldas'),
(82, N'Magdalena'),
(42, N'Aguascalientes'),
(42, N'Baja California'),
(42, N'Baja California Sur'),
(42, N'Campeche'),
(42, N'Chiapas'),
(42, N'Chihuahua'),
(42, N'Coahuila de Zaragoza'),
(42, N'Colima'),
(42, N'Distrito Federal'),
(42, N'Durango'),
(42, N'Guanajuato'),
(42, N'Guerrero'),
(42, N'Hidalgo'),
(42, N'Jalisco'),
(42, N'México'),
(42, N'Michoacán de Ocampo'),
(42, N'Morelos'),
(42, N'Nayarit'),
(42, N'Nuevo León'),
(42, N'Oaxaca'),
(42, N'Puebla'),
(42, N'Querétaro de Arteaga'),
(42, N'Quintana Roo'),
(42, N'San Luis Potosí'),
(42, N'Sinaloa'),
(42, N'Sonora'),
(42, N'Tabasco'),
(42, N'Tamaulipas'),
(42, N'Tlaxcala'),
(42, N'Veracruz-Llave'),
(42, N'Yucatán'),
(42, N'Zacatecas'),
(124, N'Bocas del Toro'),
(124, N'Chiriquí'),
(124, N'Coclé'),
(124, N'Colón'),
(124, N'Darién'),
(124, N'Herrera'),
(124, N'Los Santos'),
(124, N'Panamá'),
(124, N'San Blas'),
(124, N'Veraguas'),
(123, N'Chuquisaca'),
(123, N'Cochabamba'),
(123, N'El Beni'),
(123, N'La Paz'),
(123, N'Oruro'),
(123, N'Pando'),
(123, N'Potosí'),
(123, N'Santa Cruz'),
(123, N'Tarija'),
(36, N'Alajuela'),
(36, N'Cartago'),
(36, N'Guanacaste'),
(36, N'Heredia'),
(36, N'Limón'),
(36, N'Puntarenas'),
(36, N'San José'),
(103, N'Galápagos'),
(103, N'Azuay'),
(103, N'Bolívar'),
(103, N'Canar'),
(103, N'Carchi'),
(103, N'Chimborazo'),
(103, N'Cotopaxi'),
(103, N'El Oro'),
(103, N'Esmeraldas'),
(103, N'Guayas'),
(103, N'Imbabura'),
(103, N'Loja'),
(103, N'Los Ríos'),
(103, N'Manabí'),
(103, N'Morona-Santiago'),
(103, N'Pastaza'),
(103, N'Pichincha'),
(103, N'Tungurahua'),
(103, N'Zamora-Chinchipe'),
(103, N'Sucumbíos'),
(103, N'Napo'),
(103, N'Orellana'),
(5, N'Buenos Aires'),
(5, N'Catamarca'),
(5, N'Chaco'),
(5, N'Chubut'),
(5, N'Córdoba'),
(5, N'Corrientes'),
(5, N'Distrito Federal'),
(5, N'Entre Ríos'),
(5, N'Formosa'),
(5, N'Jujuy'),
(5, N'La Pampa'),
(5, N'La Rioja'),
(5, N'Mendoza'),
(5, N'Misiones'),
(5, N'Neuquén'),
(5, N'Río Negro'),
(5, N'Salta'),
(5, N'San Juan'),
(5, N'San Luis'),
(5, N'Santa Cruz'),
(5, N'Santa Fe'),
(5, N'Santiago del Estero'),
(5, N'Tierra del Fuego'),
(5, N'Tucumán'),
(95, N'Amazonas'),
(95, N'Anzoategui'),
(95, N'Apure'),
(95, N'Aragua'),
(95, N'Barinas'),
(95, N'Bolívar'),
(95, N'Carabobo'),
(95, N'Cojedes'),
(95, N'Delta Amacuro'),
(95, N'Falcón'),
(95, N'Guárico'),
(95, N'Lara'),
(95, N'Mérida'),
(95, N'Miranda'),
(95, N'Monagas'),
(95, N'Nueva Esparta'),
(95, N'Portuguesa'),
(95, N'Sucre'),
(95, N'Táchira'),
(95, N'Trujillo'),
(95, N'Yaracuy'),
(95, N'Zulia'),
(95, N'Dependencias Federales'),
(95, N'Distrito Capital'),
(95, N'Vargas'),
(209, N'Boaco'),
(209, N'Carazo'),
(209, N'Chinandega'),
(209, N'Chontales'),
(209, N'Estelí'),
(209, N'Granada'),
(209, N'Jinotega'),
(209, N'León'),
(209, N'Madriz'),
(209, N'Managua'),
(209, N'Masaya'),
(209, N'Matagalpa'),
(209, N'Nueva Segovia'),
(209, N'Rio San Juan'),
(209, N'Rivas'),
(209, N'Zelaya'),
(113, N'Pinar del Rio'),
(113, N'Ciudad de la Habana'),
(113, N'Matanzas'),
(113, N'Isla de la Juventud'),
(113, N'Camaguey'),
(113, N'Ciego de Avila'),
(113, N'Cienfuegos'),
(113, N'Granma'),
(113, N'Guantanamo'),
(113, N'La Habana'),
(113, N'Holguin'),
(113, N'Las Tunas'),
(113, N'Sancti Spiritus'),
(113, N'Santiago de Cuba'),
(113, N'Villa Clara'),
(12, N'Acre'),
(12, N'Alagoas'),
(12, N'Amapa'),
(12, N'Amazonas'),
(12, N'Bahia'),
(12, N'Ceara'),
(12, N'Distrito Federal'),
(12, N'Espirito Santo'),
(12, N'Mato Grosso do Sul'),
(12, N'Maranhao'),
(12, N'Mato Grosso'),
(12, N'Minas Gerais'),
(12, N'Para'),
(12, N'Paraiba'),
(12, N'Parana'),
(12, N'Piaui'),
(12, N'Rio de Janeiro'),
(12, N'Rio Grande do Norte'),
(12, N'Rio Grande do Sul'),
(12, N'Rondonia'),
(12, N'Roraima'),
(12, N'Santa Catarina'),
(12, N'Sao Paulo'),
(12, N'Sergipe'),
(12, N'Goias'),
(12, N'Pernambuco'),
(12, N'Tocantins'),
(83, N'Akureyri'),
(83, N'Arnessysla'),
(83, N'Austur-Bardastrandarsysla'),
(83, N'Austur-Hunavatnssysla'),
(83, N'Austur-Skaftafellssysla'),
(83, N'Borgarfjardarsysla'),
(83, N'Dalasysla'),
(83, N'Eyjafjardarsysla'),
(83, N'Gullbringusysla'),
(83, N'Hafnarfjordur'),
(83, N'Kjosarsysla'),
(83, N'Kopavogur'),
(83, N'Myrasysla'),
(83, N'Neskaupstadur'),
(83, N'Nordur-Isafjardarsysla'),
(83, N'Nordur-Mulasysla'),
(83, N'Nordur-Tingeyjarsysla'),
(83, N'Olafsfjordur'),
(83, N'Rangarvallasysla'),
(83, N'Reykjavik'),
(83, N'Saudarkrokur'),
(83, N'Seydisfjordur'),
(83, N'Skagafjardarsysla'),
(83, N'Snafellsnes- og Hnappadalssysla'),
(83, N'Strandasysla'),
(83, N'Sudur-Mulasysla'),
(83, N'Sudur-Tingeyjarsysla'),
(83, N'Vestmannaeyjar'),
(83, N'Vestur-Bardastrandarsysla'),
(83, N'Vestur-Isafjardarsysla'),
(83, N'Vestur-Skaftafellssysla'),
(35, N'Anhui'),
(35, N'Zhejiang'),
(35, N'Jiangxi'),
(35, N'Jiangsu'),
(35, N'Jilin'),
(35, N'Qinghai'),
(35, N'Fujian'),
(35, N'Heilongjiang'),
(35, N'Henan'),
(35, N'Hebei'),
(35, N'Hunan'),
(35, N'Hubei'),
(35, N'Xinjiang'),
(35, N'Xizang'),
(35, N'Gansu'),
(35, N'Guangxi'),
(35, N'Guizhou'),
(35, N'Liaoning'),
(35, N'Nei Mongol'),
(35, N'Ningxia'),
(35, N'Beijing'),
(35, N'Shanghai'),
(35, N'Shanxi'),
(35, N'Shandong'),
(35, N'Shaanxi'),
(35, N'Sichuan'),
(35, N'Tianjin'),
(35, N'Yunnan'),
(35, N'Guangdong'),
(35, N'Hainan'),
(35, N'Chongqing'),
(97, N'Central'),
(97, N'Coast'),
(97, N'Eastern'),
(97, N'Nairobi Area'),
(97, N'North-Eastern'),
(97, N'Nyanza'),
(97, N'Rift Valley'),
(97, N'Western'),
(195, N'Gilbert Islands'),
(195, N'Line Islands'),
(195, N'Phoenix Islands'),
(1, N'Australian Capital Territory'),
(1, N'New South Wales'),
(1, N'Northern Territory'),
(1, N'Queensland'),
(1, N'South Australia'),
(1, N'Tasmania'),
(1, N'Victoria'),
(1, N'Western Australia'),
(27, N'Dublin'),
(27, N'Galway'),
(27, N'Kildare'),
(27, N'Leitrim'),
(27, N'Limerick'),
(27, N'Mayo'),
(27, N'Meath'),
(27, N'Carlow'),
(27, N'Kilkenny'),
(27, N'Laois'),
(27, N'Longford'),
(27, N'Louth'),
(27, N'Offaly'),
(27, N'Westmeath'),
(27, N'Wexford'),
(27, N'Wicklow'),
(27, N'Roscommon'),
(27, N'Sligo'),
(27, N'Clare'),
(27, N'Cork'),
(27, N'Kerry'),
(27, N'Tipperary'),
(27, N'Waterford'),
(27, N'Cavan'),
(27, N'Donegal'),
(27, N'Monaghan'),
(50, N'Karachaeva-Cherkesskaya Respublica'),
(50, N'Raimirskii (Dolgano-Nenetskii) AO'),
(50, N'Respublica Tiva'),
(32, N'Newfoundland'),
(32, N'Nova Scotia'),
(32, N'Prince Edward Island'),
(32, N'New Brunswick'),
(32, N'Quebec'),
(32, N'Ontario'),
(32, N'Manitoba'),
(32, N'Saskatchewan'),
(32, N'Alberta'),
(32, N'British Columbia'),
(32, N'Nunavut'),
(32, N'Northwest Territories'),
(32, N'Yukon Territory'),
(19, N'Drenthe'),
(19, N'Friesland'),
(19, N'Gelderland'),
(19, N'Groningen'),
(19, N'Limburg'),
(19, N'Noord-Brabant'),
(19, N'Noord-Holland'),
(19, N'Utrecht'),
(19, N'Zeeland'),
(19, N'Zuid-Holland'),
(19, N'Overijssel'),
(19, N'Flevoland'),
(138, N'Duarte'),
(138, N'Puerto Plata'),
(138, N'Valverde'),
(138, N'María Trinidad Sánchez'),
(138, N'Azua'),
(138, N'Santiago'),
(138, N'San Cristóbal'),
(138, N'Peravia'),
(138, N'Elías Piña'),
(138, N'Barahona'),
(138, N'Monte Plata'),
(138, N'Salcedo'),
(138, N'La Altagracia'),
(138, N'San Juan'),
(138, N'Monseñor Nouel'),
(138, N'Monte Cristi'),
(138, N'Espaillat'),
(138, N'Sánchez Ramírez'),
(138, N'La Vega'),
(138, N'San Pedro de Macorís'),
(138, N'Independencia'),
(138, N'Dajabón'),
(138, N'Baoruco'),
(138, N'El Seibo'),
(138, N'Hato Mayor'),
(138, N'La Romana'),
(138, N'Pedernales'),
(138, N'Samaná'),
(138, N'Santiago Rodríguez'),
(138, N'San José de Ocoa'),
(70, N'Chiba'),
(70, N'Ehime'),
(70, N'Oita'),
(85, N'Skopje'),
(35, N'Schanghai'),
(35, N'Hongkong'),
(35, N'Neimenggu'),
(35, N'Aomen'),
(92, N'Amnat Charoen'),
(92, N'Ang Thong'),
(92, N'Bangkok'),
(92, N'Buri Ram'),
(92, N'Chachoengsao'),
(92, N'Chai Nat'),
(92, N'Chaiyaphum'),
(92, N'Chanthaburi'),
(92, N'Chiang Mai'),
(92, N'Chiang Rai'),
(92, N'Chon Buri'),
(92, N'Kalasin'),
(92, N'Kanchanaburi'),
(92, N'Khon Kaen'),
(92, N'Krabi'),
(92, N'Lampang'),
(92, N'Loei'),
(92, N'Lop Buri'),
(92, N'Mae Hong Son'),
(92, N'Maha Sarakham'),
(92, N'Nakhon Pathom'),
(92, N'Nakhon Ratchasima'),
(92, N'Nakhon Sawan'),
(92, N'Nakhon Si Thammarat'),
(92, N'Narathiwat'),
(92, N'Nong Bua Lam Phu'),
(92, N'Nong Khai'),
(92, N'Nonthaburi'),
(92, N'Pathum Thani'),
(92, N'Pattani'),
(92, N'Phangnga'),
(92, N'Phatthalung'),
(92, N'Phichit'),
(92, N'Phitsanulok'),
(92, N'Phra Nakhon Si Ayutthaya'),
(92, N'Phrae'),
(92, N'Phuket'),
(92, N'Prachin Buri'),
(92, N'Prachuap Khiri Khan'),
(92, N'Ratchaburi'),
(92, N'Rayong'),
(92, N'Roi Et'),
(92, N'Sa Kaeo'),
(92, N'Sakon Nakhon'),
(92, N'Samut Prakan'),
(92, N'Samut Sakhon'),
(92, N'Samut Songkhran'),
(92, N'Saraburi'),
(92, N'Si Sa Ket'),
(92, N'Sing Buri'),
(92, N'Songkhla'),
(92, N'Sukhothai'),
(92, N'Suphan Buri'),
(92, N'Surat Thani'),
(92, N'Surin'),
(92, N'Trang'),
(92, N'Ubon Ratchathani'),
(92, N'Udon Thani'),
(92, N'Uthai Thani'),
(92, N'Uttaradit'),
(92, N'Yala'),
(92, N'Yasothon'),
(69, N'Busan'),
(69, N'Daegu'),
(69, N'Gangwon'),
(69, N'Gwangju'),
(69, N'Gyeonggi'),
(69, N'Gyeongsangbuk'),
(69, N'Gyeongsangnam'),
(69, N'Jeju'),
(25, N'Delhi'),
(81, N'Región de Los Ríos'),
(81, N'Región de Arica y Parinacota')
GO
